common/models/Post.php
<?php

namespace common\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "post".
 *
 * @property integer $post_id
 * @property string $title
 * @property string $content
 * @property string $tags
 * @property integer $post_status_id
 * @property integer $update_time
 * @property integer $create_time
 * @property integer $author_id
 *
 * @property Comment[] $comments
 * @property Adminuser $author
 * @property Poststatus $postStatus
 */
class Post extends \yii\db\ActiveRecord
{
    public $_oldTags;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content', 'tags'], 'string'],
            [['post_status_id', 'update_time', 'create_time', 'author_id'], 'integer'],
            [['title'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'post_id' => 'ID',
            'title' => '标题',
            'content' => '内容',
            'tags' => '标签',
            'post_status_id' => '状态',
            'update_time' => '修改时间',
            'create_time' => '创建时间',
            'author_id' => '作者',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['post_id' => 'post_id']);
    }

    public function getActiveComments()
    {
        return $this->hasMany(Comment::className(), ['post_id' => 'post_id'])->where('comment_status_id=:comment_status_id',[':comment_status_id'=>2])->orderBy('comment_id');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Adminuser::className(), ['author_id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostStatus()
    {
        return $this->hasOne(Poststatus::className(), ['post_status_id' => 'post_status_id']);
    }
    //重写保存前操作，在保存前就已经设定好时间
    public function beforeSave($insert){
        if(parent::beforeSave($insert)){
            if($insert){
                $this->create_time=time();
                $this->update_time=time();
            }
            else{
                $this->update_time=time();
            }
            return true;
        }else{
            return false;
        }
    }
    //重写保存后操作，来完成标签修改
    public function afterFind(){
        parent::afterFind();
        $this->_oldTags = $this->tags;
    }
    public function afterSave($insert , $changedAttributes){
        parent::afterSave($insert,$changedAttributes);
        Tags::updateFrequency($this->_oldTags,$this->tags);
    }
    public function afterDelete(){
        parent::afterDelete();
        Tags::updateFrequency($this->_oldTags,'');
    }

    //给标题写url
    public function getUrl(){
        return Yii::$app->urlManager->createUrl(
            ['post/detail','id'=>$this->post_id,'title'=>$this->title]);
    }
    //前台列表获取内容
    public function getBeginning($length=288){
        $tmpStr = strip_tags($this->content);
        $tmpLen = mb_strlen($tmpStr);

        $tmpStr = mb_substr($tmpStr,0,$length,'utf-8');
        return $tmpStr.($tmpLen>$length?'...':'');
    }
    //获取标签
    public function getTagLinks(){
        $links=array();
        foreach(Tags::string2array($this->tags) as $tag){
            $links[] = Html::a(Html::encode($tag),array('post/index','PostSearch[tags]'=>$tag));
        }
        return $links;
    }
    //获取评论条数
    public function getCommentCount(){
        return Comment::find()->where(['post_id'=>$this->post_id,'comment_status_id'=>2])->count();
}
}

backend/controllers/PostController.php
<?php

namespace backend\controllers;

use common\models\AdminuserSearch;
use Yii;
use common\models\Post;
use common\models\PostSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access'=>[
                'class'=>AccessControl::className(),
                'rules'=>
                [
                    [
                        'actions'=>['index','view'],
                        'allow'=>true,
                        'roles'=>['?'],
                    ],
                    [
                        'actions'=>['update','create','index','view','test'],
                        'allow'=>true,
                        'roles'=>['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionTest(){
        $searchModel = new AdminuserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('test', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionIndex()
    {
//        $thepost=Post::findOne(1);
//        echo $thepost->status0->name;exit;
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(!Yii::$app->user->can('createPost')){
            throw new ForbiddenHttpException('对不起，你没有进行该操作的权限');
        }
        $model = new Post();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->post_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)       //这里的$id也代表着前台传过来的参数id
    {
        if(!Yii::$app->user->can('updatePost')){
            throw new ForbiddenHttpException('对不起，你没有进行该操作的权限');
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->post_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if(!Yii::$app->user->can('deletePost')){
            throw new ForbiddenHttpException('对不起，你没有进行该操作的权限');
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/PostController.php
<?php

namespace frontend\controllers;

use common\models\Comment;
use common\models\Tags;
use common\models\User;
use Yii;
use common\models\Post;
use common\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    public $added=0;   //有评论提交才改成1
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $tags = Tags::findTagWeights();
        $recentComment = Comment::findRecentComments();

        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'tags'=>$tags,
            'recentComment'=>$recentComment,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->post_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->post_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    //文章详细界面
    public function actionDetail($id){
        if(!isset(Yii::$app->user->id)){
            $this->redirect('index.php?r=site/login');
        }
        //1.准备数据模型
        $model = $this->findModel($id);     //文章
        $tags=Tags::findTagWeights();       //标签
        $recentComment=Comment::findRecentComments();  //评论
        $userMe=User::findOne(Yii::$app->user->id);     //获取登陆人
        $commentModel=new Comment();
        $commentModel->email=$userMe->email;
        $commentModel->userid=$userMe->id;

        //2.如果有评论提交
        if($commentModel->load(Yii::$app->request->post())){

            $commentModel->comment_status_id=1;
            $commentModel->post_id=$id;
            if($commentModel->save()){
                $this->added=1;
            }
        }

        //3.渲染视图
        return $this->render('detail',[
            'model'=>$model,
            'tags'=>$tags,
            'recentComment'=>$recentComment,
            'commentModel'=>$commentModel,
            'added'=>$this->added,
        ]);

    }

}

frontend/views/post/_comment.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php foreach ($comments as $comment):?>

<div class="comment">
    <div class="row">
        <div class="col-md-12">
            <div class="comment_detail">
                <p class="bg-info">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"><?=Html::encode($comment->user->username);?></span>
                    <br>
                    <?= nl2br($comment->content);?>
                    <br>
                    <span class="glyphicon glyphicon-time" aria-hidden="true"><?=date('Y-m-d H:i:s',$comment->create_time)?></span>
                </p>
            </div>
        </div>
    </div>
</div>

<?php endforeach;?>

frontend/views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'tags')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'post_status_id')->textInput() ?>

    <?= $form->field($model, 'update_time')->textInput() ?>

    <?= $form->field($model, 'create_time')->textInput() ?>

    <?= $form->field($model, 'author_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/post/_guestform.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;

?>

<div class="comment-form">

    <?php $form = ActiveForm::begin([
        'action'=>['post/detail','id'=>$id,'#'=>'comments'],
        'method'=>'post',
    ]); ?>

    <div class="row">
<!--        $recentComment可能为空-->
        <div class="col-md-12"><?= $form->field($commentModel,'content')->textarea(['row'=>6])?></div>
    </div>



<div class="form-group">
    <?= Html::submitButton('发表评论', ['class' =>'btn btn-primary']) ?>
</div>

<?php ActiveForm::end(); ?>

</div>

frontend/views/post/_listitem.php
<?php
use yii\helpers\Html;
?>

<div class="post">
    <div class="title">
        <h2><a href="<?= $model->url;?>"><?= Html::encode($model->title);?></a></h2>
        <div class="author">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span><em><?=date('Y-m-d H:i:s',$model->create_time); ?>&nbsp;&nbsp;&nbsp;&nbsp;</em>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span><em><?=Html::encode($model->author->name);?></em>
        </div>
    </div>

    <div class="content">
        <?= $model->beginning;?>
    </div>

    <br>
    <div class="nav">
        <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
        <?= implode(', ',$model->tagLinks);?>
        <br>
        <?= Html::a('评论'.'('.$model->commentCount.')',$model->url.'#comments');?> | 最后修改于<?= date('Y-m-d H:i:s',$model->create_time);?>
    </div>
</div>

frontend/views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'post_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'tags') ?>

    <?= $form->field($model, 'post_status_id') ?>

    <?php // echo $form->field($model, 'update_time') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Post */

$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/post/detail.php
<?php

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\grid\GridView;
use yii\widgets\ListView;
use \frontend\components\TagsCloudWidget;
use \frontend\components\RctReplyWidget;
use \common\models\Comment;
/* @var $this yii\web\View */
/* @var $searchModel common\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <ol class="breadcrumb">
                <li><a href="<?= Yii::$app->homeUrl;?>">首页</a></li>
                <li><a href="<?= Yii::$app->homeUrl;?>?r=post/index">文章列表</a></li>
                <li class="active"><?=$model->title;?></li>
            </ol>

            <div class="post">
                <div class="title">
                    <h2><a href="<?=$model->url?>"><?=$model->title;?></a></h2>
                    <div class="author">
                        <span class="glyphicon glyphicon-time" aria-hidden="true"></span><em><?=date('Y-m-d H:i:s',$model->create_time); ?>&nbsp;&nbsp;&nbsp;&nbsp;</em>
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span><em><?=Html::encode($model->author->name);?></em>
                    </div>
                </div>
            </div>
            <div class="content">
                <?= HTMLPurifier::process($model->content)?>
            </div>
            <br>
            <div class="nav">
                <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
                <?=implode(',',$model->tagLinks);?>
                <br>
                <?=Html::a('评论('.$model->commentCount.')',$model->url.'#comment')?>&nbsp;&nbsp;&nbsp;|
                最后修改于<?= date('Y-m-d H:i:s',$model->create_time);?>
            </div>

            <!--评论区-->
            <div id="comments">
                <?php if ($added)    {?>
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4>谢谢您的回复，我们会尽快审核后发布出来！</h4>
                    <p><?=nl2br($commentModel->content)?></p>
                    <span class="glyphicon glyphicon-time" aria-hidden="true"><?=date('Y-m-d H:i:s',$commentModel->create_time)?></span><!--这里为什么是model-->
                    <span class="glyphicon glyphicon-time" aria-hidden="true"><?=$model->author->name?></span>
                </div>
                <?php }?>

                <?php if($model->commentCount>=1):?>
                    <?=$this->render('_comment',array(
                        'post'=>$model,
                        'comments'=>$model->activeComments,
                    ));?>
                <?php endif?>

                <h5>发表评论</h5>
                <?php
                $postComment = new Comment();
                echo $this->render('_guestform',array(
                    'id'=>$model->post_id,
                    'commentModel'=>$commentModel,
                    'recentComment'=>$recentComment
                ));
                ?>
            </div>

        </div>
        <div class="col-md-3">
            <div class="searchhbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-search" aria-hidden="true">查看文章</span>
                    </li>
                    <li class="list-group-item">
                        <form class="form-inline" action="index.php?r=post/index" id="w0" method="get">
                            <div class="form-group">
                                <input type="text" class="form-control" name="PostSearch[title]" id="w0input" placeholder="按标题">
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>
                    </li>
                </ul>
            </div>

            <div class="tagcloudbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-tags" aria-hidden="true">标签云</span>
                    </li>
                    <li class="list-group-item">
                        <?= TagsCloudWidget::widget(['tags'=>$tags])?>
                    </li>
                </ul>
            </div>

            <div class="commentbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-comment" aria-hidden="true">最新回复</span>
                    </li>
                    <li class="list-group-item">
                        <?= RctReplyWidget::widget(['recentComment'=>$recentComment])?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

frontend/views/post/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;
use \frontend\components\TagsCloudWidget;
use \frontend\components\RctReplyWidget;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <ol class="breadcrumb">
                <li><a href="<?= Yii::$app->homeUrl?>">首页</a></li>
                <li>文章列表</li>
            </ol>
            <?= ListView::widget([
                'id'=>'postList',
                'dataProvider'=>$dataProvider,
                'itemView'=>'_listitem',    //子视图，显示一篇文章的内容
                'layout'=>'{items}{pager}',
                'pager'=>[
                    'maxButtonCount'=>10,
                    'nextPageLabel'=>Yii::t('app','下一页'),
                    'prevPageLabel'=>Yii::t('app','上一页'),
                ],
            ])?>
        </div>
        <div class="col-md-3">
            <div class="searchhbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-search" aria-hidden="true">查看文章</span>
                    </li>
                    <li class="list-group-item">
                        <form class="form-inline" action="index.php?r=post/index" id="w0" method="get">
                            <div class="form-group">
                            <input type="text" class="form-control" name="PostSearch[title]" id="w0input" placeholder="按标题">
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>
                    </li>
                </ul>
            </div>

            <div class="tagcloudbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-tags" aria-hidden="true">标签云</span>
                    </li>
                    <li class="list-group-item">
                        <?= TagsCloudWidget::widget(['tags'=>$tags])?>
                    </li>
                </ul>
            </div>

            <div class="commentbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-comment" aria-hidden="true">最新回复</span>
                    </li>
                    <li class="list-group-item">
                        <?= RctReplyWidget::widget(['recentComment'=>$recentComment])?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

frontend/views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Post */

$this->title = 'Update Post: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->post_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Post */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->post_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->post_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'post_id',
            'title',
            'content:ntext',
            'tags:ntext',
            'post_status_id',
            'update_time:datetime',
            'create_time:datetime',
            'author_id',
        ],
    ]) ?>

</div>